version: 2
updates:
  - package-ecosystem: nuget
    directory: /
    schedule: { interval: weekly }
    groups:
      microsoft: { patterns: ["Microsoft.*", "Npgsql*"] }
      openiddict: { patterns: ["OpenIddict*"] }
  - package-ecosystem: npm
    directory: /admin-console
    schedule: { interval: weekly }
    groups:
      angular: { patterns: ["@angular/*", "@angular-devkit/*"] }
  - package-ecosystem: docker
    directory: /
    schedule: { interval: weekly }
  - package-ecosystem: docker
    directory: /admin-console
    schedule: { interval: weekly }
  - package-ecosystem: github-actions
    directory: /
    schedule: { interval: weekly }
