#!/usr/bin/env bash
# Generates a LOCAL-ONLY .env for docker-compose: random passwords, a fresh self-signed signing certificate and
# fresh encryption keys. Nothing here is committed (.env is git-ignored) and nothing is reusable elsewhere.
#
#   ./scripts/dev-secrets.sh            create .env (refuses to overwrite)
#   ./scripts/dev-secrets.sh --force    replace it (existing sessions/tokens and MFA enrolments stop working)
set -euo pipefail
cd "$(dirname "$0")/.."

if [[ -f .env && "${1:-}" != "--force" ]]; then
  echo ".env already exists; use --force to replace it" >&2
  exit 1
fi

command -v openssl >/dev/null || { echo "openssl is required" >&2; exit 1; }
tmp="$(mktemp -d)"; trap 'rm -rf "$tmp"' EXIT
# native openssl on Windows (Git Bash) needs a Windows-style path; elsewhere cygpath does not exist
if command -v cygpath >/dev/null; then wtmp="$(cygpath -m "$tmp")"; else wtmp="$tmp"; fi

pfx_password="$(openssl rand -hex 16)"
# MSYS_NO_PATHCONV stops Git Bash on Windows rewriting "/CN=..." into a file path (harmless elsewhere).
MSYS_NO_PATHCONV=1 openssl req -x509 -newkey rsa:2048 -nodes -days 90 -subj "/CN=identity-signing" \
  -keyout "$wtmp/key.pem" -out "$wtmp/cert.pem"
openssl pkcs12 -export -inkey "$wtmp/key.pem" -in "$wtmp/cert.pem" -passout "pass:$pfx_password" -out "$wtmp/signing.pfx"

umask 077
cat > .env <<EOF
# Generated by scripts/dev-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ). Local development only.
IDENTITY_DB_PASSWORD=$(openssl rand -hex 16)
LEDGER_DB_PASSWORD=$(openssl rand -hex 16)
SIGNING_PFX=$(base64 < "$tmp/signing.pfx" | tr -d '\n')
SIGNING_PFX_PASSWORD=$pfx_password
TOKEN_ENCRYPTION_KEY=$(openssl rand -base64 32)
MFA_ENCRYPTION_KEY=$(openssl rand -base64 32)
BOOTSTRAP_ADMIN_EMAIL=admin@example.com
BOOTSTRAP_ADMIN_PASSWORD=$(openssl rand -base64 18 | tr -d '/+=')
LEDGER_BOOTSTRAP_API_KEY=$(openssl rand -hex 24)
EOF

echo "Wrote .env. First admin sign-in:"
grep -E '^BOOTSTRAP_ADMIN_(EMAIL|PASSWORD)=' .env
